let trainings=[];let currentFilter='全部';
const grid=document.getElementById('grid');const search=document.getElementById('search');
function clean(v){return (v===undefined||v===null)?'':String(v).trim()}
function normalizeReplay(v){const s=clean(v);if(!s)return '无录屏';if(/无|失效|缺/.test(s))return '无录屏';if(/有|包含/.test(s))return '有录屏';return s}
function deriveCategory(topic){return clean(topic).replace(/影刀\s*RPA/gi,'').trim()||'其他'}
function deriveLevel(category){if(category.includes('基础'))return '初级';if(category.includes('进阶'))return '进阶';if(category.includes('专题'))return '中级 / 专题';if(category.includes('宣讲'))return 'AI新功能';return '其他'}
function splitTags(s,title,content){let arr=clean(s).split(/[；;,，、]/).map(x=>x.trim()).filter(Boolean);if(arr.length)return arr.slice(0,6);const bag=(title+' '+content).toLowerCase();const dict=[['AI','AI'],['智能体','智能体'],['飞书','飞书'],['http','HTTP'],['api','API'],['webhook','Webhook'],['元素','元素捕捉'],['异常','异常处理'],['调度','调度'],['多维表','多维表']];return dict.filter(([k])=>bag.includes(k.toLowerCase())).map(x=>x[1]).slice(0,4)}
function splitTopics(text){return clean(text).split(/\n+/).map(x=>x.replace(/^\s*[0-9一二三四五六七八九十]+[\.、)）\s]*/,'').trim()).filter(Boolean)}
function materialLinks(text){const s=clean(text);const re=/https?:\/\/[^\s]+/g;let m,last=0,out=[],n=1;while((m=re.exec(s))){let label=s.slice(last,m.index).replace(/[\n\r]+/g,' ').replace(/[：:]\s*$/,'').trim();if(label.length>70)label=label.slice(-70);label=label.replace(/^[,，;；\s]+/,'').trim();if(!label)label=`培训材料 ${n}`;out.push({name:label,url:m[0].replace(/[，。；;）)】]$/,'')});last=re.lastIndex;n++}return out}
function fallbackTitle(row,topics,mats){if(clean(row['展示名称']))return clean(row['展示名称']);if(mats.length)return mats[0].name.replace(/[【】「」]/g,'').slice(0,38);if(topics.length)return topics[0].slice(0,38);return clean(row['培训主题'])||'未命名培训'}
function normalizeRows(rows){return rows.map((r,i)=>{const topics=splitTopics(r['培训内容']);const mats=materialLinks(r['培训材料及回放']);const title=fallbackTitle(r,topics,mats);const category=clean(r['展示分类'])||deriveCategory(r['培训主题']);const level=clean(r['培训等级'])||deriveLevel(category);const tags=splitTags(r['标签'],title,r['培训内容']);return{title,category,level,audience:clean(r['适合人群']),topics,materials:mats,replay:normalizeReplay(r['录屏状态']||r['录频回放']),tags,show:clean(r['是否展示'])!=='否',sort:Number(r['排序'])||((i+1)*10),raw:r}}).filter(x=>x.show&&x.title).sort((a,b)=>a.sort-b.sort)}
function buildFilters(){const box=document.getElementById('filters');const cats=[...new Set(trainings.map(t=>t.category).filter(Boolean))];box.innerHTML='<button class="chip active" data-filter="全部">全部</button>'+cats.map(c=>`<button class="chip" data-filter="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('')+(trainings.some(t=>t.tags.includes('AI')||/AI/i.test(t.title))?'<button class="chip" data-filter="AI相关">AI相关</button>':'');box.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>{box.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.filter;render()}))}
function escapeHtml(s){return clean(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function matches(t,q){const bag=[t.category,t.level,t.title,t.audience,...t.topics,...t.tags].join(' ').toLowerCase();return bag.includes(q.toLowerCase())}
function render(){const q=search.value.trim();const list=trainings.filter(t=>{const f=currentFilter==='全部'||(currentFilter==='AI相关'?(t.tags.includes('AI')||/AI/i.test(t.title+' '+t.topics.join(' '))):t.category===currentFilter);return f&&(!q||matches(t,q))});document.getElementById('resultText').textContent=`共 ${list.length} 个培训内容`;grid.innerHTML='';if(!list.length){grid.innerHTML='<div class="empty">暂时没有匹配的培训内容，试试其他关键词。</div>';return}list.forEach(t=>{const idx=trainings.indexOf(t);const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="topline"><span class="badge">${escapeHtml(t.category)}${t.level?' · '+escapeHtml(t.level):''}</span><span class="replay ${t.replay==='有录屏'?'':'off'}">${escapeHtml(t.replay)}</span></div><h3>${escapeHtml(t.title)}</h3><div class="audience">${escapeHtml(t.audience||'适合希望系统学习该主题的学员')}</div><div class="tags">${t.tags.map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')}</div><ul class="points">${t.topics.slice(0,3).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><div class="actions"><button class="btn primary" onclick="openDetail(${idx})">查看详情</button>${t.materials[0]?`<a class="btn" href="${escapeHtml(t.materials[0].url)}" target="_blank" rel="noopener">培训材料 ↗</a>`:''}</div>`;grid.appendChild(card)})}
function openDetail(i){const t=trainings[i];document.getElementById('mLevel').textContent=`${t.category}${t.level?' · '+t.level:''} · ${t.replay}`;document.getElementById('mTitle').textContent=t.title;document.getElementById('mAudience').innerHTML=`<b>适合人群：</b>${escapeHtml(t.audience||'—')}`;document.getElementById('mTopics').innerHTML=t.topics.length?t.topics.map(x=>`<li>${escapeHtml(x)}</li>`).join(''):'<li>暂无详细内容</li>';document.getElementById('mMaterials').innerHTML=t.materials.length?t.materials.map(m=>`<a class="material" href="${escapeHtml(m.url)}" target="_blank" rel="noopener">${escapeHtml(m.name)} ↗</a>`).join(''):'<div class="detail-sub">暂未配置材料链接</div>';document.getElementById('modal').classList.add('show')}
function updateStats(){document.getElementById('count').textContent=trainings.length;document.getElementById('categoryCount').textContent=new Set(trainings.map(t=>t.category)).size;document.getElementById('replayCount').textContent=trainings.filter(t=>t.replay==='有录屏').length}
function loadWorkbookBuffer(buf){const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});trainings=normalizeRows(rows);updateStats();buildFilters();render()}
async function autoLoad(){try{if(typeof XLSX==='undefined')throw new Error('Excel解析组件未加载');const res=await fetch('./data/培训材料.xlsx?v='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error('未找到 data/培训材料.xlsx');const buf=await res.arrayBuffer();loadWorkbookBuffer(buf)}catch(err){console.error(err);grid.innerHTML=`<div class="load-error"><b>暂时无法自动读取 Excel</b><div>如果你是直接双击本地 HTML 打开的，这是浏览器的本地文件限制；部署到 GitHub Pages / Vercel 后会自动读取。</div><label class="btn primary" for="localExcel">选择培训材料.xlsx 本地预览</label><input id="localExcel" type="file" accept=".xlsx,.xls" /></div>`;document.getElementById('resultText').textContent='等待载入 Excel';const input=document.getElementById('localExcel');input.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{loadWorkbookBuffer(await f.arrayBuffer())}catch(e2){alert('Excel 读取失败，请检查表头和文件格式。')}})}}
search.addEventListener('input',render);document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('show');document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')});
autoLoad();